#!/usr/bin/sh

if [[ $1 == "" ]]; then

	echo "Usage: sudo chmac <interface> | current | permanent"
	echo "Requirements: macchanger, ifconfig (net-tools)"

elif [[ $2 = "current" ]]; then

	echo "$(macchanger -s $1 | grep -i "current" | grep -ioe "[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}")"

elif [[ $2 = "permanent" ]]; then

	echo "$(macchanger -s $1 | grep -i "permanent" | grep -ioe "[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}:[0-9a-f]\{2\}")"

else

	sudo ifconfig $1 down
	sudo macchanger -A $1
	sudo ifconfig $1 up

fi


