#!/bin/bash

# This program is Eric Murphy's, i modified it for personal use, all credits go to him
# Requirements: amixer, pamixer

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low -r "1001" -h int:value:"$volume" -i "vol_$1" -t 2000 "Volume: ${volume}%"
}

case $1 in
up)
	pamixer -i 5 --allow-boost
	send_notification $1
	;;
down)
	pamixer -d 5 --allow-boost
	send_notification $1
	;;
mute)
	pamixer --sink 0 -t
	if $(pamixer --sink 0 --get-mute); then
		dunstify -a "changevolume" -i "vol_mute" -u low -r "1001" -t 2000 "Laptop Speaker: Muted" "Current volume: $(pamixer --get-volume)%"
	else
		dunstify -a "changevolume" -i "vol_unmute" -u low -r "1001" -t 2000 "Laptop Speaker: Unmuted" "Current volume: $(pamixer --get-volume)%"
	fi
	;;
mute_mic)
	pamixer --source 0 -t
	if $(pamixer --source 0 --get-mute); then
		dunstify -a "changevolume" -i "mic_mute" -u low -r "1008" -t 2000 "Laptop Microphone: Muted"
	else
		dunstify -a "changevolume" -i "mic_unmute" -u low -r "1008" -t 2000 "Laptop Microphone: Unmuted"
	fi
	;;
esac
