#!/bin/bash

# This program originally is Eric Murphy's, i modified it for personal use, all credits go to him!

function send_notification() {
	brightness=$(brightnessctl i | grep -o -E "[[:digit:]]{1,3}%")
	dunstify -a "changebrightness" -u low -r 1002 -h int:value:"$brightness" -i "sun" "Brightness: $brightness" -t 2000
}

case $1 in
up)
	brightnessctl set 10%+ > /dev/null
	send_notification $1
	;;
down)
	brightnessctl set 10%- > /dev/null
	send_notification $1
	;;
esac
